use printpdf::*;
use regex::Regex;
use std::io::{BufWriter, Cursor};

use crate::error::{AppError, AppResult};
use crate::models::ConvertFormat;

pub fn convert_content(
    content: &str,
    target_format: ConvertFormat,
    title: &str,
) -> AppResult<(Vec<u8>, String, String)> {
    let safe_title = sanitize_filename(title);

    match target_format {
        ConvertFormat::Txt => Ok((
            content.as_bytes().to_vec(),
            "text/plain; charset=utf-8".to_string(),
            format!("{safe_title}.txt"),
        )),
        ConvertFormat::Md => Ok((
            content.as_bytes().to_vec(),
            "text/markdown; charset=utf-8".to_string(),
            format!("{safe_title}.md"),
        )),
        ConvertFormat::Pdf => {
            let pdf = markdown_to_pdf(content, &safe_title)?;
            Ok((
                pdf,
                "application/pdf".to_string(),
                format!("{safe_title}.pdf"),
            ))
        }
    }
}

fn sanitize_filename(name: &str) -> String {
    let re = Regex::new(r#"[<>:"/\\|?*\x00-\x1f]"#).unwrap();
    let cleaned = re.replace_all(name.trim(), "-");
    let cleaned = Regex::new(r"-+")
        .unwrap()
        .replace_all(&cleaned, "-")
        .trim_matches('-')
        .to_string();
    let truncated: String = cleaned.chars().take(80).collect();
    if truncated.is_empty() {
        "omniparse-export".to_string()
    } else {
        truncated
    }
}

fn markdown_to_pdf(content: &str, title: &str) -> AppResult<Vec<u8>> {
    let (doc, page1, layer1) =
        PdfDocument::new(title, Mm(215.9), Mm(279.4), "Layer 1");
    let font = doc.add_builtin_font(BuiltinFont::Helvetica).map_err(|e| {
        AppError::Conversion(format!("PDF font error: {e}"))
    })?;
    let font_bold = doc
        .add_builtin_font(BuiltinFont::HelveticaBold)
        .map_err(|e| AppError::Conversion(format!("PDF font error: {e}")))?;

    let mut y = 260.0;
    let left = 20.0;
    let line_height = 5.5;

    {
        let current_layer = doc.get_page(page1).get_layer(layer1);
        current_layer.use_text(title, 18.0, Mm(left), Mm(y), &font_bold);
        y -= 12.0;
        let stamp = chrono::Utc::now().to_rfc3339();
        current_layer.use_text(
            &format!("Generated by OmniParse on {stamp}"),
            9.0,
            Mm(left),
            Mm(y),
            &font,
        );
        y -= 10.0;
    }

    let heading_re = Regex::new(r"^(#{1,6})\s+(.+)$").unwrap();
    let bold_re = Regex::new(r"\*\*(.+?)\*\*").unwrap();

    for block in content.split("\n\n") {
        let block = block.trim();
        if block.is_empty() {
            continue;
        }
        for line in block.lines() {
            let stripped = line.trim();
            if stripped.is_empty() {
                y -= line_height;
                continue;
            }
            if y < 20.0 {
                break;
            }

            let (text, size, bold) = if let Some(caps) = heading_re.captures(stripped) {
                let level = caps.get(1).map(|m| m.as_str().len()).unwrap_or(1);
                let body = caps.get(2).map(|m| m.as_str()).unwrap_or("");
                (body.to_string(), if level <= 2 { 14.0 } else { 12.0 }, true)
            } else if let Some(body) = stripped.strip_prefix("- ").or_else(|| stripped.strip_prefix("* ")) {
                (format!("• {body}"), 11.0, false)
            } else {
                (stripped.to_string(), 11.0, false)
            };

            let rendered = bold_re.replace_all(&text, "$1").to_string();
            let clipped: String = rendered.chars().take(95).collect();
            let layer = doc.get_page(page1).get_layer(layer1);
            if bold {
                layer.use_text(&clipped, size, Mm(left), Mm(y), &font_bold);
            } else {
                layer.use_text(&clipped, size, Mm(left), Mm(y), &font);
            }
            y -= line_height;
        }
        y -= 3.0;
    }

    let mut buffer = BufWriter::new(Cursor::new(Vec::new()));
    doc.save(&mut buffer)
        .map_err(|e| AppError::Conversion(format!("PDF generation failed: {e}")))?;
    Ok(buffer.into_inner().map_err(|e| AppError::Conversion(e.to_string()))?.into_inner())
}
