import asyncio
import io
import re
from datetime import datetime, timezone

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

from app.core.exceptions import ConversionError
from app.models.schemas import ConvertFormat

_HEADING_RE = re.compile(r"^(#{1,6})\s+(.+)$")
_BOLD_RE = re.compile(r"\*\*(.+?)\*\*")
_LINK_RE = re.compile(r"\[(.+?)\]\((.+?)\)")


def convert_content(content: str, target_format: ConvertFormat, title: str) -> tuple[bytes, str, str]:
    safe_title = _sanitize_filename(title)

    if target_format == ConvertFormat.TXT:
        return content.encode("utf-8"), "text/plain; charset=utf-8", f"{safe_title}.txt"

    if target_format == ConvertFormat.MD:
        return content.encode("utf-8"), "text/markdown; charset=utf-8", f"{safe_title}.md"

    if target_format == ConvertFormat.PDF:
        pdf_bytes = _markdown_to_pdf(content, title=safe_title)
        return pdf_bytes, "application/pdf", f"{safe_title}.pdf"

    raise ConversionError(f"Unsupported target format: {target_format}")


def _sanitize_filename(name: str) -> str:
    cleaned = re.sub(r'[<>:"/\\|?*\x00-\x1f]', "-", name.strip())
    cleaned = re.sub(r"-+", "-", cleaned).strip("-")
    return cleaned[:80] or "omniparse-export"


def _markdown_to_pdf(content: str, *, title: str) -> bytes:
    try:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=0.75 * inch,
            leftMargin=0.75 * inch,
            topMargin=0.75 * inch,
            bottomMargin=0.75 * inch,
            title=title,
        )

        styles = getSampleStyleSheet()
        story = [
            Paragraph(f"<b>{_escape_xml(title)}</b>", styles["Title"]),
            Spacer(1, 0.2 * inch),
            Paragraph(
                f"<i>Generated by OmniParse on {_escape_xml(datetime.now(timezone.utc).isoformat())}</i>",
                styles["Normal"],
            ),
            Spacer(1, 0.3 * inch),
        ]

        for block in content.split("\n\n"):
            text = block.strip()
            if not text:
                continue

            for line in text.split("\n"):
                stripped = line.strip()
                if not stripped:
                    story.append(Spacer(1, 0.08 * inch))
                    continue

                heading_match = _HEADING_RE.match(stripped)
                if heading_match:
                    level = len(heading_match.group(1))
                    style_name = "Heading1" if level <= 2 else "Heading2"
                    story.append(
                        Paragraph(_markdown_inline_to_reportlab(heading_match.group(2)), styles[style_name])
                    )
                    continue

                if stripped.startswith(("- ", "* ")):
                    story.append(
                        Paragraph(
                            f"&bull; {_markdown_inline_to_reportlab(stripped[2:])}",
                            styles["BodyText"],
                        )
                    )
                    continue

                story.append(Paragraph(_markdown_inline_to_reportlab(stripped), styles["BodyText"]))

            story.append(Spacer(1, 0.12 * inch))

        doc.build(story)
        return buffer.getvalue()
    except Exception as exc:
        raise ConversionError(f"PDF generation failed: {exc}") from exc


def _markdown_inline_to_reportlab(text: str) -> str:
    escaped = _escape_xml(text)
    escaped = _BOLD_RE.sub(r"<b>\1</b>", escaped)
    escaped = _LINK_RE.sub(r'<link href="\2" color="blue">\1</link>', escaped)
    return escaped


def _escape_xml(value: str) -> str:
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )
